#+STARTUP: showall
#+STARTUP: logdone
#+STARTUP: lognotedone
#+STARTUP: hidestars
#+FILETAGS: hide
#+OPTIONS: broken-links:t
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/org/Bibliography/Literatur authoryear-ibid
#+TODO: TODO(t) STARTED(s!) WAITING(w@/!) APPT(a) PROJ(p) NOTIZ(n) BESPROCHEN(b) DELEGATED(g@/!) | DONE(d!) ZKTO(z) CANCELED(c@)
#+SETUPFILE: ~/org/latex_setup.org
#+TITLE: dreifaltigkeit
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com


Ich freue mich, dass Sie die Videos ansehen (hoffentlich auch ganz - und von vorne). Dass Sie es nicht verstehen, tut mir leid und kann verschiedene Ursachen haben: Ich erkläre es schlecht. Oder ich erkläre etwas Falsches und sehe die eigenen Widersprüche nicht. Oder ich rede zu kompliziert, weil ich nach 9 Jahren Studium an der Uni ein Doktorat in Theologie besitze und Dinge in einem Dialog voraussetze, die ich nicht voraussetzen sollte. Denn vielleicht besitzen die Leute, die sich dieses Video ansehen und kommentieren ja keine fachliche Qualifikation oder universitäre Bildung und ich springe über die Schritte, die notwendig sind, um es verständlich zu machen zu schnell hinweg. Das wären alles Szenarien, wo die Schuld für Ihr fehlendes Verständnis ganz bei mir liegt. Möglich wäre natürlich etwas anders: Sie versuchen meine Position gar nicht zu verstehen, sich auf christliche Terminologie und Theologie einzulassen und arbeiten lieber mit Ihnen vertrauten religiösen Vorurteilen, egal ob diese auch dem christlichen Glauben entsprechen. Das tat übrigens schon der laut muslimischen Quellen ungebildete Mohammed, der Maria für einen Teil der Dreifaltigkeit hielt und Geschichten aus gnostischen apokryphen Texten für Gottes Wort, oder die Torah mit dem Talmud verwechselte..und all dies dann unwissend zu einem Teil seiner göttlichen Offenbarung erklärte.). Das ist menschlich und Muslime wie auch Christen agieren in dieser Hinsicht aus dem Reflex meist gleich. Wir verteidigen, was wir glauben schneller, als wir andere verstehen. Egal wo nun der Fehler liegt - oder liegt er gar bei beiden? - versuche ich es hier neuerlich mit einer Antwort: 
Ganz allgemein: Nach Auffassung der alten christlichen Kirchen ist Gott nicht ein mächtiges Wesen, das man nur nicht verstehen kann, weil es viel größer ist als wir, sondern die Natur Gottes ist für uns generell nur analog zu begreifen - sprich, alles was wir über Gott sagen und als Menschen notwendigerweise dafür menschliche (und damit limitierte) Begriffe benutzen ist Gott aus diesem Grund auch immer unähnlich. Wir können Gott nicht eingrenzen. Das gilt es zu bedenken, bevor wir überhaupt anfangen, über Gott und sein Wesen zu reden. Und die muslimischen Philosophen der goldenen Epoche des Islam stimmen hier durchwegs überein. 
Es stimmt, dass die Gesetze der Logik gelten (sein != nicht sein), sonst könnten wir gar keinen sinnvollen Austausch pflegen. Und damit man hier keine Fehler macht muss man (wie immer in der Logik, um keinem Fehlschluss aufzusitzen) differenzieren. Denn der häufigste Fehler in der Logik ist wohl die Äquivokation, d.h. das Verwenden des selben Begriffes für Verschiedenes. Damit würde jedoch jeder Syllogismus wertlos und ein Trugschluss. Dies geschieht auch in Ihrer Antwort, wenn sie vom Willen des Vaters und des Sohnes reden. Sie projezieren undifferenziert menschliches Handeln auf ein göttliches Wesen (2 göttliche Personen) und sehen keine Möglichkeit zur Einheit, weil zwei Willen bei uns Menschen auch immer zwei Wesen implizieren. Hier ist was Christen glauben: Gott ist einer hinsichtlich seiner Natur und drei hinsichtlich der Personen. Das ist kein logischer Widerspruch, weil sich eins und drei nicht auf den gleichen Aspekt beziehen. Kann man sich das vorstellen? Nein. Denn wir können uns nur mit Bildern etwas vorstellen, die aus unseren Sinnen kommen. Über unsere Sinne haben wir aber nur Vorstellungen von Geschöpfen, nicht vom Schöpfer (wenigstens nicht was sein Wesen betrifft). Das bedeutet nicht, dass man nicht zur Wahrheit kommen kann, sondern dass nicht jede Wahrheit vorstellbar ist (= wir können uns kein Bild davon machen). Wir können uns in diesem Sinn kein Bild von Gott machen wie wir uns auch kein Bild der Unendlichkeit machen können und in diesem Sinn auch beides nicht "verstehen" (="eingrenzen"). Das heißt wie gesagt nicht, dass man die Tatsache der Unendlichkeit oder das Konzept nicht erfassen kann - oder etwas über das Wesen Gottes aussagen - nur eben ist bei Letzterem Vorsicht angebracht, weil es nur analog sein kann. Gott hinsichtlich seinen Handelns und Denkens mit Menschen zu vergleichen hilft nichts, weil Gott nicht wie ein Mensch ein zusammengesetztes Wesen ist, in dem es Teile gibt (das müssten eigentlich auch Muslime glauben, um das Tauhid nicht zu verletzen) und Personen in Gott nicht wie beim Menschen durch Materie in separate Individuen gefasst werden. Gott ist nicht materiell; Personschaft nicht die Instantiation einer übergeordneten Natur. 
Christen glauben wegen der Offenbarung Jesu, dass die Dreifaltigkeit eine treffende Wesensbeschreibung Gottes ist (= 1 Natur in 3 Personen und zwar nicht additiv, sondern die EINE göttliche Natur ist dreifaltig). Es gibt demnach einen einzigen Gott in drei Personen - unterscheidbar übrigens allein im Hinblick auf ihre Beziehung zueinander. Nichts daran widerstrebt den Gesetzen der Logik - die übrigens von christlichen Denkern als philosophische Disziplin zu einer Zeit schon Jahrhunderte lang kultiviert wurden, als man sich in Mekka noch Götzen niederwarf. Im islamischen Raum hält Logik als Disziplin erst durch die Angriffskriege der Muslime und die gewaltvolle Unterwerfung christlicher Gebiete Einzug, wo die muslimischen Eroberer auf die Kultur und die Philosophie des hellenistischen Westens stoßen. Das bringt später interessante philosophische Entwicklungen durch große muslimische Denker wie ابن رشد hervor - die Auswirkungen auf die christliche Philosophie im Mittelalter haben sollten - auch auf als Problem der Doppelwahrheit zum Beispiel). Aber genug zur Logik. Was nun betrifft den Willen Jesu? Die zweite Person der Dreifaltigkeit (Gottes ewiges Wort /der Logos /der Selbstausdruck Gottes) hat die menschliche Natur angenommen (d.h. einen menschlichen Leib und menschliche Seele zu seiner göttlichen Person hinzugezogen, um für uns sichtbar zu werden). In Christus finden sich demnach dann auch zwei Willen: der göttliche, weil er eine göttliche Person ist (die 2. Person der Dreifaltigkeit). Der göttliche Wille des Sohnes findet sich im Einklang mit dem göttlichen Willen des Vaters (was nicht bedeutet, dass sie ident sind). Jesus hat ferner, zweitens, einen menschlichen Willen, weil Christus eine menschliche Natur angenommen hat. Dieser menschliche Wille Jesu (so wie der menschliche Intellekt Jesu) ist menschlichen Gesetzen und Grenzen(!) unterworfen, weil Christus wahrhaft eine menschliche Natur hat. Der menschliche Wille Jesu ist unabhängig vom göttlichen, aber steht ebenfalls (durch die tugendhafte Ordnung der menschlichen Strebkräfte in Christus) im Einklang mit seinem göttlichen Willen (ohne dabei ein und das selbe zu sein). Wir sehen zum Beispiel das Wirken der Gefühle auf den Willen (wie bei jedem Menschen) in der Passion Jesu und die bleibende Unterordnung des menschlichen Willens Jesu unter den göttlichen Willen. Nichts davon ist ein logischer Widerspruch, vorausgesetzt ich stelle mir Gott nicht als riesengroßen Menschen vor, der wie ein Mensch funktioniert. Nun gibt es ja muslimische Gelehrte, die darüber diskutierten ob Allah einen Körper hat (wegen den Versen im Koran, die solches beschreiben) - philosophisch wäre dies ein Todesstoß für Allahs Allmacht (und Allah wäre nicht so viel anderes wie die Gottheiten, die man gemäß den satanischen Versen anbeten durfte, als Mohammed mal kurz vom Teufel getäuscht wurde....). Aber wenn Gott geistig ist, dann kann man auch die personelle Einheit in der menschlichen Natur und ihren Funktionen nicht zum Maßstab (oder gar zum Bild) der dreifaltigen göttlichen Natur machen und einen Pluratlität einführen, die dort nicht existieren kann. Ist das kompliziert? Ja. Zeus wäre einfach. Oder ein Spaghettimonster. Denn diese einfachen Götter sind im Grunde nur mächtige Wesen, die die Welt regieren. Sie funktionieren so wie Menschen. Ihr Maß ist der menschliche Verstand, der sie erfunden hat. Und genau darum hat es keinen Sinn an sie zu glauben.
