#+TITLE: Klaus Berger

[[https://www.youtube.com/watch?v=Zz7CwEeznag]]

Theologie benötigt eine Reformation.

Kath. Systematiker: "Dreifaltigkeit ist eine Erfimdung des MA. Lassen wir sie beiseite - so gäbe es keine Konflikte mit Juden uns Islam." MA war gut für Fabeln; ein unpersönlicher Gott wäre besser. Das nennt man Deismus!

Welcher Dogmatiker sieht die Dreifaltigkeit als Fundament des Christentums? Gibt es sie? Leider - kaum.

Exegese ist fast immer Kirchenkritik, weil man Zölibat, etc nicht will.

Karl Rahner (dt. Idealismus) / Walter Kasper (Bultmann in Reinkultur) ... hier fühlt sich K. Berger nicht wohl. Hr. Zollitsch (Bischof): "ich leugne den Sühntod Jesu. das sind MA Vorstellungen. Jesus dem Menschen im Sterben nahe."

Zur Auferstehung - dominierende Vorstellung: Gott habe am Glauben der Jünger gerhandelt, aber nicht am Leib Jesu. Jesus ei im Grab verwest; die Jünger sind zu der besseren Überzeugung gekommen, dass Jesus doch der Sohn Gottes sei.
Die Frage ist: wo handelt Gott? An den Herzen der Jünger? Oder an der Person Jesu? Das ist für moderne Menschen ein Ärgernis.

Was ist Wirklichkeit? Wie wird sie wahrgenommen? Die Wissenschaftler haben oft ihre Sicht erweitert ... SIE sind keine fundament. Psotivisten. Die Theologen sehen die WS aber so ...

Die Bibel sollte so ausgelegt werden wie im 6. und 7. Jahrhundert (Beatus von Liebana). 
