:PROPERTIES:
:ID:       82113972-037b-4307-a67d-dc4df041c4a9
:END:
#+title: 2021-08-24
* 11:06 : Aha, das letzte Ding (% p) funktioniert nicht.
* 23:37: Ah, jetzt klappt es!
Die Zeit wird richtig angezeigt.
* 13:18: Kinderzimmer Ausmalen
Wow - gestern Nachmittag / Abend habe ich das Kinderzimmer ausgemalt.

Zuerst wurde das Zimmer ausgeräumt; dann habe ich jene Bereiche mit Krepp-Klebeband abgeklebt, die ich nicht anmalen möchte. Leider war ich dabei etwas zu sparsam.

Beim Malen habe ich zuerst mit den Rändern mit einem kleinen Pinsel begonnen. Durch meine Recherche wusste ich, dass man den Rest der Wand mit der Rolle oder dem großen Pinsel fertigmalt. Wichtig ist, dass man dabei zügig die Wand ausmalt, um Streifenbildung zu vermeiden.

Nacheem ich die erste Wand fertig hatte, wollte ich eigentlich aufhören - aber ich besann mich eines Besseren und malte die zweite Hälfte ebenso. Eine Schwierigkeit war dabei der Teppich. Diesen musste ich mühsam in den Gang schaffen, somit konnte ich mit besser den nötigen Platz verschaffen.

[[id:16328745-d6ca-4f21-902d-ce8920412ed9][2021-08-25]]




