#+TITLE: Emacs
#+STARTUP: logdone
#+STARTUP: lognotedone
#+STARTUP: hidestars
#+TODO: TODO(t) STARTED(s!) WAITING(w@/!) APPT(a) PROJ(p) NOTIZ(n) BESPROCHEN(b) DELEGATED(g@/!) | DONE(d!) ZKTO(z) CANCELED(c@)

* Linux
Ich habe das Gefühl, dass ich dieses tolle Betriebssystem noch nicht voll ausnutze. Was mir unter anderem fehlt, ist das Programmieren. Daher muss ich ein paar Programmiersprachen erlernen. Womit beginnt man? Was sind Basis-Kenntnisse? Python, C++, Ruby; etwas Altes wie Basic, Pascal? Scheme?

* Emacs
Das ist so ziemlich das coolste Programm, das es gibt. Ist er ein Editor? Eine Entwickler-Umgebung (IDE)?

Was kann er:
 - Content-aware editing modes, including syntax coloring, for many file types.
 - Complete built-in documentation, including a tutorial for new users.
 - Full Unicode support for nearly all human scripts.
 - Highly customizable, using Emacs Lisp code or a graphical interface.
 - A wide range of functionality beyond text editing, including a project planner, mail and news reader, debugger interface, calendar, IRC client, and more.
 - A packaging system for downloading and installing extensions.
 - Twitter, RSS-Feed, WWW, LaTex, etc. 
   
Bei Emacs kopiere ich bis jetzt Elisp-"Stücke" in meine .emacs-Datei. Irgendwo habe ich gehört, dass man 10 Jahre braucht, um ihn zu verstehen. Habe ich nicht ein Buch über diese Programmiersprache?

* Intellektuelle Herausforderungen
Ich muss mehr in meine Aus- und Fortbildung investieren. Z.B. meine Bachelor-Arbeit weiterschreiben. Diese habe ich ziemlich "verhunzt" - ich kann jetzt gar nicht mehr sagen, was das "Ergebnis" dieser Arbeit ist. Natürlich war es von Seiten der KPH nicht okay, da Herr Pernjak kurzfristig vor der Abgabe (nov) das Thema geändert hat. Die ursprüngliche Forschungsfrage bleibt für mich unbeantwortet: Wie können wir über Gott als Vater reden, wo doch viele Kinder ohne Vater aufwachsen? Darüber habe ich zwei Studien, allerdings außerhalb der Religionspädagogik. Die sollte ich lesen, durcharbeiten und eine Beziehung zur Religionspädagogik herstellen. Die Frage, welche W. Pernjak gestellt hatte (v.a. bei der Defensio): "Inwiefern sind die aktuellen Reli-Bücher noch verwendbar?" - so verstand ich's. Denn tatsächlich verwenden so gut wie keine Reli-Lehrer diese Bücher. 
