#+TITLE: V_Frankl

* Gesehen werden
Geschichte einer jungen Frau; Jahrhundert-Wende. Ehe als Arrangement, Reichtum. Kein erfülltes Leben, unglücklich. Allerdings den Künsten aufegschlossen. Portrait von Gustav Klimt. Der Maler betrachtete die Frau lange, viele Sitzungen - bis zum Portrait: Julia Klipps (?). Ein wohlwollender Blick kann Menschen verwandeln. 

Wenn ein Mensch zutiefst verstanden wird - das prägt - das heilt. Z.B. Günther von seinem Vater verstanden werden. 

Vielleicht werden viele meiner Schüler nicht gesehen?

Existentielle Fragen interessiert die Schüler viel mehr als Themen wie Liturgie, Heilige, Sakramente, ...

* Konkrete Mittel
Ein Schüler "nervt" - wiederholt: Da Silva (mex. Psychiater) - Für jenen Schüler *beten*, ihn segnen, über ihn Gutes denken. Sicher hat sich auch etwas in der Lehrerin verändert durch das Gebet. 

Wie gehe ich mit mir selber um? Mit welcher Haltung gehe ich in den Unterricht? 

Humor - *mit* dem Schüler lachen. Persönliche Gespräche: auf jeden Fall besser als "Schimpfen". 

* Literatur von / zu Viktor Frankl
cf Internet; 

 - ... trotzdem Ja zum Leben sagen. Ein Psychologe erlebt das Konzentrationslager
Wenn ich denke: Ah, jetzt weiß ich's! - Dann klappt es nimmer.
Viktor Frankl - im KZ: "Endlich meine Frau wiedersehen!" - erfährt, dass seine Frau getötet wurde. Frankl hat bald darauf seine Erlebnisse diktiert. Im KZ: wir werden uns jeden Tag einen Witz erzählen (Abmache mit einem Mithäftling). Neben dem Brutalen gibt es auch Anderes: Sonnenuntergang ansehen. 

 - Haddon Klingberg: Das Leben wartet auf dich – Viktor & Elly Frankl

 - Jörg Riemeyer: Die Logotherapie Viktor Frankls und ihre Weiterentwicklungen. Huber, Bern 2007, ISBN 978-3-456-84448-0

 - Was nicht in meinen Büchern steht. Lebenserinnerungen. (Frankl)

 - Der unbewußte Gott. Psychotherapie und Religion (Frankl); 2. Dissertation (Philosophie) - cf. Rahner 

Beispiel: [Gleichnis von den 10 Talenten] Jemandem wird etwas anvertraut (mit einem Vermögen); jeder erhält seins, jeder anders; Verantwortung; Was bei dir dein Schatz? Wo ist dein Herz? Wonach sehnst du dich? Du brauchst keine Angst haben. 

Gebetserziehung - werde still, gehe in dich; Gott ist im Verborgenen. Bei Jahrestagung auch in sich gehen, auf dich schauen.

Methode "Existentieller Stadtrundgang"; als Übung - auf Schüler abwandeln. Cf. Zettel. Bereich für Bereich pro Stunde. 

