#+STARTUP: showall
#+STARTUP: logdone
#+STARTUP: lognotedone
#+STARTUP: hidestars
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+TITLE: JFK_Ganser

Notizen zu einem YouTube-Video von Daniele Ganser zum Mord an John F. Kennedy in Dallas 1963 (Texas)

These von D. Ganser: CIA-Chef Allan Dullas - von JFK entlassen - befiehlt den Mord an JFK.
Warum?

1961: USA - Cuba: Fidel Castro stürzen. Exil-Kubaner sollten Kuba über die Schweinebucht infiltrieren und Castro und Ernesto "Che" Guevara stürzen.
(Illegal) 
1953: Iran - Sturz der Regierung von Mossadek
1954: Guatemala - Sturz der Regierung von A...?

Präsident Eisenhower (Vorgänger von JFK) hat die geheime Invasion von Kuba geplant.
JFK führt die Invasion aus.

Invasion: zuerst die Luftwaffe ausschalten, dann mit Schiffe. Deshalb ließ Dullas die Flugzeuge umbemalen. Castro schoß die Bomber ab und entdeckte die Täuschung. 

Botschafter Kubas kritisierte die Bombardierung. US-Botschafter: "Nein, das waren die enttäuschten Kubaner. Haben ihr eigene Land angegriffen." Castro blieben noch ein paar Flugzeuge, mit denen griff er die Boote an. Invasion beendet - Niederlage der CIA. Dullas hat verloren. JFK: Pentagon einschalten? Er entschied sich dagegen! Leute des Pentagon und der CIA sind furchtbar wütend auf den Präsidenten. Die Wut JFKs traf Dullas und Richard Bissell (Chefplaner der verdeckten Operationen) und entließ beide. Sie waren überzeugt, dass Kennedy ein Sicherheitsrisiko für die CIA und die imperialen Interessen der USA darstelle. 

Ohne Beweis - doch deutet vieles darauf hin, dass Dullas den Auftrag zur Ermordung JFKs gab. 

1964: Krieg gegen Vietnam (bis 1975). JFK wollte diesen Krieg nicht. [Robert S. McNamara: In Retrospect - The Tragedy and Lessons of Vietnam. 1995]

Dullas hatte eine Mord-Gruppe, spezalisiert auf Staatschefs. Senator Frank Churxh deckte dies 1975 auf - er Untersuchte CIA-Mordanschläge.[fn:1] 

Das Wiederholen - so funktioniert das Gehirn! Allen Dullas war Chef der CIA und hatte eine Kommission für Mordaufträge. ABER: ich kann meine Nervenzellen selber lenken, indem ich etwas Anderes wiederhole. 

Richard Bissell ab 1961: Aufbau einer Abteilung für Mordaufträge "Executive Action". Chef der Abteilung: William Harvey. Mehrere Versuche: vergiftete Zigarren; Zusammenarbeit mit der Mafia (John Rosselli) - Castro überlebte; 

Kongo: Belgien beuteten Kongo aus; erster Präsident Patrice Lumumba (1960); Belgien + CIA: "Gehts noch?" Mord an Patrice Lumumba (17.1.1961). Auftrag zum Mord kommt von Eisenhower, nicht von JFK. Kennedy erfährt davon und ist entsetzt! Zeuge der Sitzung: Schockstarre - bestürztes Schweigen, 15 Sekunden lang, als Eisenhower den Befehl gab.[fn:2]

Vietnam: Präsident Dien, korrupt; wurde ermordet (Selbstverbrennung von buddhistischen Mönchen).[fn:3] 

(Buch: 100 Seiten pro Tag lesen ist normal - das ist Training. Völlig egal, welches Thema! Also, was lese ich? Religös, zB Guardini? Oder Ganser? Oder Geschichte Mittelmeer?) 

Harvey Oswald wird verdächtigt, JFK ermordet zu haben (sofort nach dem Mord). Diese Nachricht geht stark und direkt rein. 7 Monate lang im "Tiger"-Aufmerksamkeit-Zustand zu sein: Erschöpfung. Oswald sagt: "Ich bin nur der Sündenbock!" Prozess? Jack Ruby erschießt Oswald. Verhör ohne Protokoll bei Oswald in der Polizei. Jack Ruby verstirbt an Krebs im Gefängnis, eigentlich zu Tode verurteilt. Warren-Kommission soll Mord aufklären: Sept. 1964 - wer ist in der Kommission? Allen Dullas! Johnson wollte nicht, dass der Mord aufgeklärt werde. (Dreifach Mord - perfekter Mord!) 

1966: Mark Lane deckt auf - JFK wurde von vorne erschossen! Er prüfte Zeugenaussagen: "Kennedy wurde von vorne erschossen!"[fn:4] Seine Arbeit stützt sich auf 50 Zeugenaussagen. Jim Garrison (Film JFK von Oliver Stone 1991) fiel auf, dass die Route kurzfristig geändert wurde. Der Nitrattest entlastete Oswald, denn dadurch wurden keine Schmachspuren an seinen Händen nachgewiesen.[fn:5] Außerdem war er ein sehr schlechter Schütze, kaum aggressiv, und das Gewehr ear sehr schlecht. 

CIA verwanzte sein Büro. Richard Helms, Direktor CIA, ließ durch seine Leute das Team um Garrison infiltrieren. 

Film von Abraham Zapruder: Kennedy wurde von vorne getroffen, da sein Kopf nach hinten gerissen wurde.[fn:6]

Life Magazin kaufte den Film und verhinderte die Veröffentlichung; erst 1969, 6 Jahre später, zeigte Jim Garrison den Film das erste Mal öffentlich. Oliver Stone bringt das Original von Zapruder; er wurde nicht vom Pentagon unterstützt - ein gutes Zeichen.

Leichnam von JFK wurde entführt, aus dem Spital. Es geschah keine Autopsie. [Stop bei 1:19:50]

* Footnotes

[fn:6] [[https://www.youtube.com/watch?v=Zmz4lz6l8Fs]] 

[fn:5] Jim Garrison "Wer erschoss John F. Kennedy", Gustav Lübbe 1992, S. 127.   

[fn:4] Mark Lane "Rush to Judgement", 1966; ebenso ein Dokumentarfilm mit gleichem Titel. [[https://www.youtube.com/watch?v=0w4sQtwWfBo]]

[fn:3] Quelle Quelle: [[file:~/Downloads/CIA-Alleged Ass Plots Foreign Leaders.pdf]] S. 5 

[fn:2] Quelle Daniele Ganser Imperium USA, S. 174 

[fn:1] Quelle: [[file:~/Downloads/CIA-Alleged Ass Plots Foreign Leaders.pdf]] 
