#+STARTUP: showall
#+STARTUP: logdone
#+STARTUP: lognotedone
#+STARTUP: hidestars
#+TITLE: Notenkonferenz_200706.org
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com

* Notenkonferenz NMS Golling

** Begrüßung
amtliche Dinge sind weitergeschickt; Mails durchlesen.

** Testung
Safia + Maid bleiben sitzen; und?
Test kann in den ersten Schulwochen wiederholt werden.
Bringt nur bei Maid etwas: dadurch wird er ordentlich, womit alles benotet wird. Wie helfen wir ihm besser? Maid nächstes Jahr ordentlich beurteilen wird nichts bringen, da er sehr faul ist. Elternsgespräch sinnvoll.

** Stunden
Fix: eine neue Lehrerin (Turnen Mädchen und IKT)
4.. Stunden und sind nicht in der Lage, alle D-Stunden abzudecken; wir müssen Stunden einsparen. Daher Leistungsgruppen wie in Mathematik (?)

Kompetenzraster werden kommen

** Planung nächstes Jahr
Stundenplan (1 Dienstposten ist frei); Info ab Mittwoch; wir brauchen mehr Mathe (und auf lange Sicht D)-Lehrer;

Pädag: Kurse anmelden; SCHILF (6 Stunden) miteinrechnen: für alle Interessierte und "Betroffene"

Schulbücher-Lehrer-Exemplare: kommen alle in die Direktion!
Ansichtsexemplare Platz im Konferenz-Zimmer, zur Verfügung zu stellen für alle. Fächer (offene) neu umräumen.
Religionsbücher einsammeln und verräumen!

** Pausenaufsichten
Besonders in der Früh: bitte pünktlich sein! Desinfektionsmittel für die nächsten Jahre noch eingedeckt, weil wir leider wenig desinfizieren. 

** Noten eintragen
Interimsbestätigungen erst nach der Notenkonferenz

<2020-07-06 Mo> Gruppe B - alles mitnehmen und Spint leer räumen. L der letzten / 6. Stunde
<2020-07-06 Mo> Gruppe A - alles mitnehmen und Spint leer räumen. L der letzten / 6. Stunde

Klasseneinteilung für nächstes Jahr nohc nicht offiziell, da wir noch nicht wissen, ob wir eine i-Klasse haben (oder nicht). 

Einkaufsliste auf die Homepage. (Plastikumschläge - oder nicht; lange / sinnlose Diskussion)

** Räume:
1a (ehem Wolfi)
1b im 2. Stock 
1c im 2. Stock Gertraud
2a + 2b bleiben
3a + 3b
4a + 4b bleiben; 4c zieht in den 1. Stock (Smartboard)

<2020-07-08 Mi> Generalprobe 4. Klassen für ihre Feier

** 4. Klassen Feier
Eis vom Elternverein
Bitte Eis beim Café Maier holen und in der Schule verteilen

Donnerstag Gruppe B Zeugnis
<2020-07-09 Do 8:00> Gottesdienst für die 4. Klassen
<2020-07-09 Do 10:00> Abschlussfeier 4. Klassen

Freitag Zeugnis Gruppe A
<2020-07-10 Fr 10:00> Schlusskonferenz + Jause

Wie geht's im Herbst weiter? Reißverschlusssystem viel besser. Es muss nach Stundenplan gearbeitet werden - auch besonders zuhause! (und nicht um Mitternacht HÜ abgeben) Wir müssen rigoroser "reinfahren"! Schüler in der Betreuung kommt in der Schule, weiß, dass er D machen muss - und hat D Sachen vergessen. Weil es den Schülern sch...egal ist. 

Wir orientier(t)en uns zu lange an denen, die schwach sind. 

Durch die zwei Leistungsgruppen können wir besser differenzieren - und schärfer sein.  

** Notenkonferenz
Vierte Klassen (Jahres- und Abschlusszeugnis); 10.7.2020; Noten ausgeschrieben
9. Schuljahr: keine Verhaltensnoten
Klauseln eintragen!

Fehlstunden nicht im Zeugnis

1. - 3. Klassen: EDEL berechnen ("Zeugnisdruck")

Verhaltensnoten?
WZ - keins

Nicht Genügend
1a 1x D
2a 1x D
3b 4x (ein Schüler: D E M GW) er dreht eine Ehrenrunde.
etc...

3c: Colin kann aufsteigen?!

** Allfälliges
Sport-Magazin kann man einsparen

