#+STARTUP: showall
#+STARTUP: logdone
#+STARTUP: lognotedone
#+STARTUP: hidestars
#+TITLE: Konferenz
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com

* Konferenz NMS Golling

** Amtliches
8 Lehrer wollen hierher! Nicht alle werden kommen können (Dienstalter)
Unser absolutes Ziel: bisherige Lehrer wollen wir halten! Aber wir haben es nicht in der Hand.

Christoph zieht seine Kandidatur zurück - leider! 
Gründe: Kommunikation mit Amt - nicht vorhanden. Bsp. Am Mittwoch nach Pfingsten müssen wir Dinge umsetzen, die am Samstag Abend per Pressekonferenz verkündet wurden. Kein Rückhalt durch Amt!

** Schule intern 
Es dringt viel nach außen: Pausenaufsicht, Frühaufsicht! Kinder in die Garderobe begleiten bei Unterrichtsende.

Leidiges Thema Leistungsbeurteilung - den Kindern mitteilen, was gemacht wurde. Keine Hemmungen mehr. Die Kinder müssen rein kommen, wenn sie nichts machen. Plan: Wer ist da? Wann ist er da? Was hat er zu tun? Damit die Betreuungslehrer wissen, was sie kontrollieren sollen. Und: wann der Schüler nach Hause gehen kann.

Schüler "Ich brauch aber..." = schlechtes Argument! Wir Lehrer brauchen, dass der Schüler arbeitet. Bei manchen Schülern genügt ein Anruf beim Vater.

Google Classroom - gute Kontrolle

BSP: bis zu Schulschluss gestrichen; oder freiwillger Ergänzungsunterricht? Müssen Sportlehrer entscheiden. Schulautonom beschlossen: BSP findet wegen fehlender Sinnhaftigkeit nicht statt.

Abschlussfeier der 4. Klassen für *alle* (Änderung!)

Bzgl Schulgottesdienst:
 - ab 1.7. in der Kirche Veranstaltungen mit 250 Menschen; Abstandregeln
 - Konkrete Vorschläge:
   - Gottesdienst für beide 4. Klassen in der Pfarrkirche
   - Oder: Gottesdienst für ganze Schule am Egelsee (Steintisch)

Zwei Gottesdienste:
 - 4. Klassen
 - 1-3 Klassen
... als dritte Alternative.

Gesundheitskabarett, 4. Klassen: letztes Jahr war es "unterste Gürtellinie"; kein Problem, wenn es nächstes Jahr ausfällt. 

Smartboard bitte ausschalten in der sechsten Stunde! (3a, 3b, 4a) Beamer + Glühbirne tauschen: 1.400 Euro Kosten. Bei Nicht-Funktionieren bitte zu Irmi gehen und melden.

Schulautonomer Tag: wer nicht da ist, bitte melden (Lehrer). Wenn jemand nicht da ist: bitte Supplierung vorbereiten. 

Schwerpunkt 2020/2021: Informatik wie bisher wird nicht möglich sein, da Christian in Pension geht. Personal: Erich könnte IKT abdecken? Zu BSP-Schwerpunkt gehen keine sportlichen Kinder, sondern jene: die weder IKT noch E gehen können. Dh BSP-Schwerpunkt breiter aufstellen; und 2wöchig geblockt. 

Welche Schwerpunkte:
 - Englisch
 - Ernährung Gesundheit Bewegung (oder teilen?)
 - 

Interessen der jetztigen 2. Klassen:
 - 2a Volleyball
 - technisches Werken
 - ?

Wenn kein Personal da ist, kann auch ein best. Schwerpunkt nicht angeboten werden. Vom Status quo ausgehen: welcher Lehrer ist da? Was können wir anbieten? 


