#+STARTUP: showall
#+STARTUP: logdone
#+STARTUP: lognotedone
#+STARTUP: hidestars
#+TITLE: Schlusskonferenz_200710.org
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com

* Begrüßung
Versetzungen - wir wissen noch nichts. Fix ist: Julia Brandlehner (M, BSP, IKT; 11 Stunden). Fr. Steinberger (Land) erachtet es als nicht dringend, uns zu informieren (wer, welche Fächer, wieviele Stunden).

* Rückblick
Kursanmeldungen (Fortbildung) sind seit 1.7.2020 möglich.

DANKE für gestriges Fest; Zeitung; (Druckerei Hauser; 5,50 Euro / Exemplar, 100 Stück). Es war sehr viel Arbeit, Schüler mussten ständig motiviert werden. Jeder Schüler hat seinen Beitrag geleistet.

Danke für das Kontrollieren der Klassenbücher - wer noch nachtragen muss: bis Ende nächster Woche muss es erledigt sein.

Interessensfächer:
 - DGI: 9
 - E: 15
 - EGB: 12

Schüler, erste Klassen: 59
Lehrfächerverteilung noch völlig offen.

* Organisation Schuljahr 2020 / 2021
Viele Kinder wiederholen - in welche Klassen kommen sie?

Erste Klassen: Maid, (1 Mädchen)
Zweite Klassen: 
Dritte Klassen: Fabio (3a); 

Schema und Ebu hätten Anspruch auf Wiederholungsprüfung - nehmen sie es in Anspruch? eher nicht. Beide steigen mit einem Nicht Genügend auf. 

Lehrerausflug: wo? wie? wann? eventuell im Oktober - in Österreich.
Halbzeitfeier: 12. August 2020; Göllhof.

14. September 2020, 7h45 - 9h30: für alle Klassen Schulbeginn (hoffentlich "völlig normal"). Erste Klassen Einkaufsliste.
10h00: Eröffnungskonferenz
im Anschluss: Fachkonferenzen (Planung der Einstufung)
Dann: Jause (geht auf Barbara, falls Hochzeit stattfindet - juhuu!)

* Allfälliges
Gibt's noch was?
DANKE an alle von Elfi und Christoph! DANKE von uns an euch!
