#+STARTUP: showall
#+STARTUP: logdone
#+STARTUP: lognotedone
#+STARTUP: hidestars
#+TITLE: Autismus
#+AUTHOR: Matthias Fuchs

Autismus

* Beeinträchtigung der exekutiven Funktionen

 - Bedürfnis nach Gleicheit
 - Schwierigkeiten in der Aufmerksamkeitausrichtung
 - Perseverationstendenz
 - Mangelnde Impulskontrolle
 - Selbständiges vorausschauendes Handeln
 - Unvorhergesehene Ereignisse - Neuorientierung

 - hauptsächlich sind die Flexibilität und Planung betroffen

Turnen ist für einen Autisten eher schwierig, weil zu Infos auf einmal einprasseln. Vielleicht eine fixe Aufgabe? Nur Schiri sein? Genau ausmachen: So hast du eine positive Stunde erledigt. 

* Der Arbeitsspeicher 
hat bei Autisten begrenzt. Sie "behirnen" alles - benötigen viel Energie. Je mehr Autisten bedenken müssen ...

* Schwache zentrale Kohärenz
Einzelne Informationen werden zu einem Gesamtbild zusammengefügt. Höhere Bedeutung im gesamten Kontext.

Autisten sehen zuerst die Details. Sie müssen zuerst dekodieren und analysieren. Bitte an die Lehrer: Filtert vor!

* Die Theory of Mind
Die spezielle geistige Fähigkeit, sich in andere hineinzuversetzen, um deren Wahrnehmungen, Gedanken und Absichten zu verstehen. 
Sammelbegriff für Empathie und Einfühlungsvermögen

Vorstellungen, Ideen, Gefühle, Gedanken, Wünsche, etc. bei anderen zu erkennen.

Bsp.: wenn ich das tu, dann wird die L gerade Kino für mich. Aber er erkennt nicht, dass die L wütend wird. 

Entwickelt sich ab dem 3. Lebensjahr. Erkennen des Unterschieds zwischen eigenen und fremden Annahmen. Bewusstsein über verschiedene Bewertungen des gleichen Ereignisses von verschiedenen Menschen.

"Schimpfen" im normalen Tonfall mit normalem Gesicht. Autismus ist keine Krankheit - können nicht gesund werden. 

* Das soziale Gehirn
Spiegelneuronen - wenn sich jemand in den Finger schneidet, dann empfinden wir mit, zeigen ebenfalls "Symptome". Basis für Empathie. Wo stehe ich im Raum? Wo stehen die anderen im Raum? Wie wird sich der andere bewegen? Vorhersehen der Handlungen anderen. Autisten haben hier eine Schwäche - sie lernen nicht am Modell. 

Kennt Paul die Namen? Gesichter erkennt er gut. Ja - S und L. 

* Verzehrte Wahrnehmung
Sinne werden nicht gut verarbeitet, va das Zusammenwirken. Sie hören alles gleich laut. Kein Filtern. Keine Selektion. "Cocktail-Party". Sehr schnell reizüberflutet - daher leicht aggressiv. 

Was hast du gut gemacht? Was kannst du? Konsequente, klare Regeln (wäre für alle Kinder besser). Konsequenzen: bedeutet nicht Strafen, sondern - ich weiß, was als nächstes kommt. 

Ihn persönlich ansprechen; klare Pläne; Lärmempfindlich ist er nicht. Wettkämpfe: "Jetzt wird es laut!" Urangst: etwas verpassen. Daher: "Die Information, die du hast, die passt so / stimmt."

Autismus ist keine Ausrede, nichts zu tun. Skikurs ist zwar eine große Herausforderung, aber er braucht ihn. Allerdings wird er seine Auszeiten benötigen.  

