#+STARTUP: showall
#+STARTUP: logdone
#+STARTUP: lognotedone
#+STARTUP: hidestars
#+title: Ruinierte Wirtschaft, kaputte Kultur
#+roam_key: https://www.youtube.com/watch?v=Di0PI2tLsL4

* Daten
pro Tag erhalten 200 Menschen die Diagnose "Krebs"
pro Tag sterben 70 Menschen an Krebs

Durch Corona wurde die Krebs-Vorsorge (Unter- und Fehlversorgung) massiv eingeschränkt.

Gibt's Zahlen dazu?

Hilfeschrei der Kinderpsychiatrie: sind überfüllt!

Warum wird der Lockdown verlängert und verlängert; die Spitäler nicht überfüllt sind. Und der einzige rechtliche Grund für den Lockdown ist die Überlastung des Gesundhseitssystems. Warum wird also der Lockdown verlängert?

Jeder, der 48 Stunden vor seinem Tod pos. auf Covid getestet wurde - gilt als Covid-Toter (auch wenn die tatsächliche Todesursache eine andere war). Dh doch, dass wir die Zahlen nicht mehr ernst nehmen können.

Nichts tun geht nicht. Welche Maßnahmen setzt man - zu welchem Preis? Welchen Preis zahlen wir im Moment?
 - gesundheitlicher Preis
 - wirtschaftlicher Preis

Verteilung ist unterschiedlich: wer wird arbeitslos? etc. Es ähnelt einer Chemotherapie: der Tumor muss kleiner werden, daher hochdosierte Chemo, egal welche Medikamente, welche Zusammensetzung, egal wie es dem Patienten dabei geht, ...

Verhältnismäßigkeit wurde nicht gewahrt. Daher andere Maßnahmen?
Nein - wir haben es nicht geschafft, eine Datengrundlage zu schaffen! Welche Maßnahme in welchem Paket wie wirkt? Das wissen wir nicht! Hier liegt der Hund begraben!

Wir haben mehr Nebenwirkungen als Wirkung (gegen den Virus). Daher machen auch viele Menschen nicht mit; Gefahr von sozialen Verwerfungen und Konflikten. Abstumpfungen; keine Konsistenz und vor allem Widersprüche in den Maßnahmen.

Bsp. am ehesten infiziert man sich in Innenräumen - warum daher Ausgangssperren? Eigentlich sollte man die Menschen dazu animieren, hinauszugehen und sich zu bewegen!? Test beim Frisör darf nicht älter als 48 Stunden sein / mobile Pflege darf eine Woche alt sein.

1,7 Mio. Tests in der Schule in einer Woche / das haben wir in der Alterspflege nie geschafft!

