:PROPERTIES:
:ID:       7bfe7495-a1fb-4ff2-8681-b793ede7d3a4
:END:
#+title: Eröffnungskonferenz


* Begrüßung
Neuer Lehrer: Bernhard Moser

Hochzeit: Julia Hofer

Jubilare: Hannes, Astrid, ...

Yunus: Papa von Mädchen


* Schulprofil, zeitgemäße Schulordnung, Verhaltenscodex
Teams erstellen diese Texte.

* Covid-Maßnahmen

** In den ersten drei Schulwochen:
3x pro Woche getestet (1x externer PCR Test) (für Lehrer)
PCR Test am Dienstag; unaufgefordert das Formular vorlegen.

Externer PCR Test: Kuchl, alte Turnhalle (über salzburg-testet anmelden; keine Kosten). Antigen-Test (Nase) von Montag gilt bis Mi Früh / am Dienstag nach der Schule muss ich PCR Test machen. Alte Turnhalle: im Markt bei Ampel links; gegenüber ist Metzger Gumboldt (?).

** Nach den ersten drei Schulwochen:


** Außerhalb der Unterrichtsräume MNS tragen

** Hygienebeauftragte: Manuela Singer
sie erklärt Maßnahmen, v.a. Tests.

* Weiteres:
 - Welche Mankos bestehen bei Schülern vom letzten
 - 1,5 Stunden pro Klasse für Förderstunden
 - vertstärkt schulpsychologische Angebote für Schüler
 - Kontrolle der persönlichen Daten!
 - Hat sich Adresse etc geändert?
 - Sitzplan / Gruppenplan / ...
 - 17.9.: Deadline Reli-Abmeldung
   Unterschrift beider Eltern / oder des Erziehungsberechtigten (wenn alleinerziehend)


 
* PH Fortbildung
Veranstaltungen werden in unterrichtsfreie Zeit verlagert

Rückmeldungen an PH senden!

* LFV und Stundenpläne
...

Gangaufsicht

* Klassenzahlen
1A 21
1B 18
1C 20
2A 21
2B 19
2C 22
3A 24
3B 23
4A 18
4B 17

* Schulbücher!
KVs: genaue Schulbücheranzahl kontrollieren. Fehlende Bücher werden nachbestellt.
Überschüßige Bücher bitte NICHT verwenden, Namen .... sondern zurückgeben!

Gesagt.

* Administratives

** Schule 
Pünktlichkeit
Tafel löschen nach jeder Stunde
Aufräumen, mit Klasse in Garderobe
Jause: Zweierreihe
Pausen: Fenster gekippt
Große Pause: 10h25 erster Stock / 10h30 zweiter Stock (ungerade Wochen Wechsel)
Handys: ausgeschaltet im Spint!
Schülern müssen Schulpflichtsaufgaben vermittelt werden.

** Schulfreie Tage:
26.10.-02.11. Herbstferien

Vorschläge:
7.01. (Weihnachtsferien wären drei Tage länger), 27.05. (Chr. Himmelfahrt), 17.06. (Fronleichnam)

** Kustos:
Matthias Religion
         Schulbücher

** Klassenvorstände:
1A Bernhard Moser 27.9. Forum
1B Wolfgang
1C Daniela
2A Magdalena 22.9. Forum?
2B Erwin
2C Waltraud 
3A Irina 5.10. Forum 
3B Christoph 
4A Mirjam Seiwald 
4B Gertraud Viertbauer

** Elternsprechtag
Erster Termin: 29.11.2021, 15h00-19h00
Zweiter Termin: 27.4.2022, 15h00-18h00
KEL-Gespräch: (im Zuge des E-Sprechtages)

?wöchentliche Sprechstunde - verpflichtend?

** Sitzung Krisenteam


** Brandschutzübung

** Weihnachtsgottesdienst
23.12.2021, 11h30
Elisabeth anrufen 

** Tag der offenen Tür
22.11.-26.11.2021

** Semesterferien
12.2. - 20.2.2022

** Semsterkonferenz

** Skikurs
März 2022

** Anmeldung Schule

** Ostergottesdienst
8.4.2022, 11h30

** Sportwoche (3. Klasse)
bis Samstag 

** Wientage (4. Klasse)
Oktober / Covidregeln von Wien (2G)

** Sportwoche (4. Klasse)
bis Freitag 

** Schwerpunktwoche?
Sinnhaftigkeit steht im Raum - wǵegen Terminhäufigkeit!

** Wandertage
Mittwoch: allg. Wandertag
Donnerstag: 
Freitag: dritte Klassen in Salzburg 


* Allfälliges

** IT - 8 Punkte Plan
um im Falle eines Lockdowns FIT zu sein: (ich frage nochmals Julia)

1. Teams / Classroom Gruppen erstellen (nach den Vorgaben)
2. Erste Klassen müssen sich alle einmal einloggen (Account wird aktiv)
3. Digi4School / Codes eingeben
4. Alle Passwörter kontrollieren (2.-4. Klassen); ev. in den Planer reinschreiben!
5. Windows-Tablets mit Tastatur und Stift (Selbstbehalt 100 Euro; 25%)

Allg. Anm.: Schulleiter sind mit admin. Tätigkeiten überfordert, und haben keine Sekretärin.

WLAN hat (im letzten Schuljahr) nicht in allen Klassen funktioniert: jetzige 4. Klassen / ehem. 4C

** QMS
Umfrage

Plan für drei Jahre erstellen / IT hinzunehmen

** Wiederholunsgprüfungen
Daniel: nein
Dalal: nicht erschienen

zwei haben es geschafft

** ab Mittwoch Unterricht nach Plan 

** PCR Spültest
Mo: Antigen (2 Tage)
Di: Spültest (3 Tage) - Ergebnis am Mittwoch 
Fr: Antigen (2 Tage)

Bzgl. Spültest:
- Röhrchen mit Lösung
- Spülen
- zurück ins Röhrchen
- Sticker auf Verschluss
- zweiter Sticker in den Ninja Pass ?
  
Genauste Zahlen über Menge der Tests.

Vorschriften durchlesen!

Um 8h30 müssen alle Tests bei Birgit sein - werden vom Logistikdienst abgeholt!



