#+TITLE: Berger2004: Jesus
#+ROAM_KEY: cite:Berger2004

- tags :: [[file:01_Golling.org][02_Golling.org]] 
- keywords :: 

* Jesus
:PROPERTIES:
:Custom_ID: Berger2004
:URL: 
:AUTHOR: Berger, K.
:NOTER_DOCUMENT: 
:NOTER_PAGE:
:END:
S. 99: Gerne wird alles Leid der Erde an uns Christen geschickt - wer sind wird, dass wir Gott verteidigen müssten? Warum von Gott ein Wunder fordern, wo sich Erdplatten gegeneinander verschieben?

Was sagt die Bibel? (äußerste Distanz, Erschrecken) Gott ist heilig (erschütternd, befremdlich, gefährlich, in die Knie zwingend, groß und unfassbar). Ein Abglanz von Gottes Heiligkeit sind die Gesetze der Natur.

[s. 100:]
Komisches Gottesbild: Gottes Liebe ist grenzenlos. Ist Gott jetzt eher wie eine zärtliche Mutter? Gott als Gummiwand universalen Verzeihens? Kann man daher mit Gott ganz locker umgehen? Gott ist einfach immer nur lieb... Wirklich? Diesen Gott braucht niemand mehr fürchten - und in Konsequenz nimmt niemand mehr diesen Gott ernst. So ein Gott ist harmlos. So wie bei (großen) Hunden: "Keine Angst, der tut nichts!" Dieser Gott tut auch nichts: nichts was uns schadet; nichts, was uns gegen das Böse in der Welt schützt. Er greift nicht mehr ein - Gott wird belanglos.

[S. 101:]
Bibel: Gott ist wie ein Hammer, der Felsen zerschmettert. Wer Gott sieht, der vergeht, der stirbt. Durch Gottes Klarheit wird die ganze Wahrheit und Armseligkeit des Menschen sichtbar. Das heilige Erschrecken ist nicht die krankmachende Angst. Unendliche Differenz zwischen Gott und dem Menschen: Ehrfurcht und Gottesfurcht.

 - Gott so lieben, dass man nichts anderes zu viel liebt.
 - Gott so fürchten, dass man vor nichts anderem zu viel Angst hat.

Schrecken hat etwas mit Gott zu tun. Lk 13,1-5.

[S. 102:]
Durch unser Tun haben wir längst den Tod verdient: und das nicht, weil sich Gott das ausgedacht hat, sondern weil es gerecht ist. Gerechtigkeit ist maßgeblich für das Verständnis von Wirklichkeit. Katastrophen dienen uns als Warnung. Bei Gott sein als sein Kind - die Botschaft Jesu; und dennoch weiß das NT um die Folgen des normalen Sünderseins. Wer auf der Erde den Mut hat, eine Ausnahme mitten im Zeitgeist zu sein, für den gilt: bei Gott sein als sein Kind.

Das Normale ist: wir sterben als normale Sünder in unseren Sünden, der Tod holt uns zur Gänze ein (AT und NT).

[S. 103:]
Wir lassen Abtreibung per Krankenkassa finanzieren, aber die Geburt eines Kindes müssen wir selbst bezahlen (D?) - da gilt die Kultur des Todes! Wer für das Leben eintritt, gilt als "intolerant und Fundamentalist"!

"Betroffenheit" - die neue Religion.

[S. 104:]
Die Psychologie hält Einzug in die Seelsorge. Es wird nach Traumata gesucht - statt Sünden vergeben. Die "Seele" steht hoch im Kurs. Nur findet man Gott. Logisch, dass man dann keine Kirche mhr benötigt. Daher will man nix mehr Jesus zu tun haben. Wer will denn dauernd betroffen sein, weil ihm gesagt wird, er sei ein Sünder? Daher treten wiele aus der Kirche aus: das ist Psychoterror. Die habe kein Verhältnis zur Lebensfreude.

[S. 105:]
Wo es keine persönliche Schuld mehr gibt, finden moderne Theologen "sündige Strkturen in der Kirche".

 - Verdrängung
 - Persönliche Schuld wird pauschal auf die Kirche abgeschoben: Entlastung
 - Betroffenheit: Was sollen wir denn schon tun? Wir können doch gar nichts machen - ist halt so.

[S. 106:]
Wir sind Sünder - oh, das macht mich betroffen! Was sollen wir denn tun? Jesus sagt nicht immer: "Deine Sünden sind dir vergeben!" Oder: "Mach mal Yoga, Feldkrais-Diät!" Sondern: "Gebt ihr ihnen zu essen! Wenn ihr nicht emdenkt, dann werdet ihr genauso umkommen!"

[S. 107:]
Jesu Blick geht nach außen. Schau nicht auf dich, sondern blick auf mich (Jesus), was ich habe, bin und will. Jesus ist der, dein Herr. Betroffenheit ist wie Pietismus ohne Gott - Selbsterkenntnis gibt es auch ohne Gott.

Logik der Herrlichkeit: ein betender Christ rechnet mit Wundern. Wunder sind nicht auf Lourdes beschränkt. Christen rechnen mit Wundern.

[s. 108:]
Mut der Missionare; in den Bürgerkriegen und Katastrophen in Afrika und Asien verkünden junge Christen Jesus. Sie handeln auf Jesu Wort hin.

Ohne dem Turmerlebnis hätten die Oberen Luther in die Mission schicken müssen - denn Martin Luther war gefangen in sich selbst. 

[s. 109:]
Die ganze Wirklichkeit ist größer als die fünf Brote und zwei Fische (Starren auf Kirchenaustritte, etc) - Jesus hat damit 5000 Menschen satt gemacht und es blieben 12 Körbe voll über. Aber wie begegnen wir Jesus wirklich? (so wie sich Maria Magdalena zweimal zu Jesus umdreht) Durch Kontemplation. Contemplata tradere - als Bibelwissenschaftler.

[S. 110]
Jugendliche: Orientierung und innere Hand, sichere Rituale und Sehnsucht nach Gesprächen.

Wir können nur das glaubhaft weitergeben, wovon wir selbst durchdringen haben lassen: die Eintönigkeit der Kontemplation. 


